### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by SyncMaster93** [Crypto137/MHServerEmu#105]
Tutorial how to install this.. thanks

**Comment by Crypto137** [comment]
We have setup instructions in our documentation [here](https://github.com/Crypto137/MHServerEmu/blob/master/docs/Setup/InitialSetup.md). If you still have issues, you can ask for help in our [Discord server](https://discord.gg/hjR8Bj52t3) in the setup-help channel.

**Comment by SyncMaster93** [comment]
> We have setup instructions in our documentation [here](https://github.com/Crypto137/MHServerEmu/blob/master/docs/Setup/InitialSetup.md). If you still have issues, you can ask for help in our [Discord server](https://discord.gg/hjR8Bj52t3) in the setup-help channel.

thanks
