### ISSUE TITLE
Love that this is a project, here is some issues I have encountered!

### ISSUE THREAD

**Issue by DSonOfTheSea** [Crypto137/MHServerEmu#106]
- Enemies with machine guns do not hit at range or at all
- Hero abilities with guns ie. Blade machine gun skill, does not hit
- Skills dont use spirit at all
- certain passive hero abilities dont trigger
- Certain melee movent skills dont do anything ie. ghost riders melee bike move

These are just 2 heros i played thus far to lvl 12 and 14, i am assuming there is plenty more skills/ mechanics not working as intended just wanted to bring these to your attention!

Ghostrider clip
- https://www.twitch.tv/dsonofthesea/clip/ScaryAwkwardLasagnaWTRuck-vx4kwpjO8YuGwYwg
- 
Blade clip
- https://www.twitch.tv/dsonofthesea/clip/CorrectArbitraryChickpeaBudBlast-mGL405xuoqdQA7Nz

**Comment by Crypto137** [comment]
Hello. We are aware of all of these issues, they are caused by the fact that certain power-related systems are not yet implemented.
