### ISSUE TITLE
Discord Invite Expired

### ISSUE THREAD

**Issue by trippsc2** [Crypto137/MHServerEmu#49]
Hello,

It looks like the Discord invite link has expired.

**Comment by Crypto137** [comment]
Hello,

The invite link we have in the readme file shows up as active on Discord. Can you clarify what link do you mean and/or what error message do you get?

**Comment by trippsc2** [comment]
![Screenshot_20240315_145214](https://github.com/Crypto137/MHServerEmu/assets/46848743/f079472e-2dfd-4097-b133-092167b2de84)

Attached is a screenshot of what I see.

**Comment by Crypto137** [comment]
Please try this link: https://discord.gg/dfZfsM4GSA

If it doesn't work, please let me know what you Discord username is.

**Comment by trippsc2** [comment]
Seems to have been a web authentication issue with Discord.  I copied the invite link into the desktop app and it worked perfectly.

Sorry for the false alarm.
