### ISSUE TITLE
Version 1.49?

### ISSUE THREAD

**Issue by MartinSokolov15** [Crypto137/MHServerEmu#78]
Hi, great work! Can it work with v1.49? Or can you direct me where to find v2.16a?

**Comment by Crypto137** [comment]
MHServerEmu requires client version 1.52.0.1700 (referred to as 2.16a in the official patch notes). You can download this version from Steam if you still have the game in your library, or look around the Internet on websites like Archive.org. This is the only currently compatible version of the game.

**Comment by MartinSokolov15** [comment]
Yes, i read the patch notes. Buti cant find newer version.

**Comment by SinisterSpatula** [comment]
send me a DM on the discord if you need more help

**Comment by MartinSokolov15** [comment]
> send me a DM on the discord if you need more help

Can't find you there. Any other way to contact you?
